# Generated by Django 3.2.4 on 2021-06-03 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='most_similar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='back.Word'),
        ),
    ]
