# Generated by Django 3.2.4 on 2021-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210603_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='words',
            field=models.ManyToManyField(blank=True, to='back.Word'),
        ),
    ]
