# Generated by Django 3.2.4 on 2021-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='most_similar',
        ),
        migrations.RemoveField(
            model_name='song',
            name='vector',
        ),
    ]
